Feat/company graphql example
rivierapartners/presidio pull request #29
Opened 2021-07-14 23:37 UTC by curtisnn

Example using graphql

2021-07-14 23:37 UTC, deus-ex-rivina commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **curtisnn**
You can assign the PR to them by writing `/assign @curtisnn` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=rivierapartners%2Fpresidio).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/rivierapartners/presidio/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["curtisnn"]} -->

2021-07-14 23:38 UTC, deus-ex-rivina commented
@curtisnn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 8e5a421af9a16b86026f336b3c65c756143f2b4b | [link](https://dashboard-jx.jx.riviapps.com/namespaces/jx/pipelineruns/ivierapartners-presidio-pr-29-pr-8277p) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-07-15 00:30 UTC, patrickleet requested changes

2021-07-15 21:41 UTC, deus-ex-rivina commented
@curtisnn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | c38cb9da39ece6b7119bce2b2df64a6d5ad5bcb7 | [link](https://dashboard-jx.jx.riviapps.com/namespaces/jx/pipelineruns/ivierapartners-presidio-pr-29-pr-4dmlh) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-07-16 19:02 UTC, merged